### PR TITLE
[New] Old Sundanese corpus - JatiMula

### PR DESCRIPTION
**Pull request by Ilhamkang**
Dear @arlogriffiths & @aditiagunawan, I have uploaded raw materials of Jati Mula text from Perpusnas RI and Ciburuy. 
Please check the files and hopefully they can be accepted. 

Thank you.

### CODE REVIEW

**Comment by arlogriffiths** [comment]
Dear @Ilhamkang ,

Thanks a lot. I have just merged your pull request so we now have the folder https://github.com/erc-dharma/tfd-nusantara-philology/tree/master/ilham.

I am passing this on to @ajaniak for further processing.

Dear Axelle,

Please give Ilham direct access to tfd-nusantara-philology and create a participant ID for him (which will be ilnu).

If I understand correctly, Ilham has delivered four files (two txt, two docx) to be converted to two diploEd files in xml:
	•  ilham/JatiMula-Ciburuy-diplEd.odt
	• ilham/JatiMula-Ciburuy-diplEd.txt
	• ilham/JatiMula-PerpusnasL1097peti69-diplEd.docx
	• A ilham/JatiMula-PerpusnasL1097peti69-diplEd.txt 

He has also delivered one docx which might be used as basis for a critEd file, though I am not sure about this:
	• ilham/Rekonstruksi jatimula Perpusnas & Ciburuy.docx

I don’t know what is to be done with 	
	•  ilham/.~lock.JatiMula-PerpusnasL1097peti69-diplEd.docx# (1)
	• ilham/PNRI 277 Peti 89 CaritaWiwitJatiLuput.txt

@Ilhamkang : could you clarify what should be done with the last three files?

Best wishes,

Arlo

**Comment by Ilhamkang** [comment]
Thank you @arlogriffiths for merging the files! 

There are three sources that contain Jati Mula text. 
1. A bundle of gebang manuscript L1097  from National Library of Indonesia (ms A) 
2. A lontar manuscript from Ciburuy, which the folios are scattered on several bundles. (ms B) 
3. A transliteration (copy/edition?) of gebang manuscript (L1097) by Holle (or Pleyte?/ inventory number 277) in the National Library of Indonesia.        

About the three last files: 
1. ilham/Rekonstruksi jatimula Perpusnas & Ciburuy.docx - this is a comparative tabulation guide to trace the position of pages from those three sources. 
2. ilham/.~lock.JatiMula-PerpusnasL1097peti69-diplEd.docx# (1) - a temporary files which produces during working on the word processor. Please delete this file.  
3. ilham/PNRI 277 Peti 89 CaritaWiwitJatiLuput.txt - This file has a complete transliteration of L1097 by Holle. When I've checked the manuscript bundle, it has a missing folio. So this file can be a witness for that missing folio.  
 
Best regards, 
Ilham

**Comment by ajaniak** [comment]
Dear @arlogriffiths and @Ilhamkang, 

I have provided an access to the repository, filled in the participant list and made a first draft for the 3 diplomatic editions. However, I don't understand all its content so I couldn't make transform all as it should. If you provide some directions, I can do it though. Could you fill in the metadata and provide the filename? 

The first draft have been pushed in editions folder of the repo and a first automatic display is available from https://erc-dharma.github.io/tfd-nusantara-philology/index-diplomatic.html

Best, 
Axelle

**Comment by arlogriffiths** [comment]
Thanks a lot Axelle! I will study this with Ilham and we will open one or more github issues if we require your help.

Warm greetings,

Arlo

**Comment by Ilhamkang** [comment]
@ajaniak thank you for the access and the 3 drafts of diplomatic editions. 

I will try to tidy up the editions and fill in the metadata one by one. I've also made some tweaks on L 1097 edition to match the DHARMA transliteration system.

Here is the case I found on working these editions: 
1. Manuscript L 1097 is in good condition except one folio is lost. 
2. Ciburuy's manuscript has many folios that lost. The Roman foliation number (r/v) is rather confusing since they are scattered across bundles. So the folio numbers could be from each different bundles or perhaps from the original bundle (I presume the second option is more possible, but still need confirmation).  The increasing original number (in old Sundanese script) in several folios is also promising as a reconstruction guide. The reconstruction is also possible through the text comparison with other witnesses which I've made on the table file.
5. The edition of  PNRI 277 was typed by a friend. The text numbering is not based on pages, but using paragraph numbers. Does it need to be changed to folio format for edition consistency?  

Sincerely, 
Ilham

**Comment by arlogriffiths** [comment]
dear @Ilhamkang !

let us discuss these matters together, you and I, before getting back to Axelle, because her role is not to help us with factual matters, only with the technical aspects.

certainly, yes, if you have images of PNRI 277, the diplomatic edition should be restructured with reference to pages numbers `<pb>` and line numbers `<lb>`. 

however, I guess the same file can also be used as a starting point for a critical edition, and Axelle could format it as such, using semantic tags (paragraph numbers `<p>`) rather than physical ones, if you confirm that this file is a good base text for creating a critical edition — i.e., it contains the whole text in correct sequence. Ihaven't looked at rthe XML code so I don't know how obvious the paragraph divisions are. give Axelle any help she might need, if indeed you wish her to set up a base file for the critical edition.

do you have access to our googledoc with the (nearly finished) encoding guide for critical editions?

best,

Arlo

**Comment by Ilhamkang** [comment]
Ah! OK @arlogriffiths. Let's discuss the factual matters then, also with @aditiagunawan, I think. 

I agree to use the PNRI 277 file as the base for critical edition because it is the most complete witness. 

As for @ajaniak, there are several codes that can be read as follow: 
1. paragraph, page, & line number 
	<X3.20-38> = page 3. line 20-38
	<X3.39-4.12> = page 3. line 39 - page 4. line 12
	<X4.13-21> = page 4. line 13-21 ... and so on.
2. pages separated by symbol | 
3. folio number on the manuscript: [[number]]
4. comments/footnote by Holle: [f.comment] 
5. emendation: [/comment]   

Best, 
Ilham

**Comment by ajaniak** [comment]
I have pushed the developed version for the PNRI 277 diplomatic edition and created a critical edition with this text under the name JatiMula for which the metadata and the witnesses will need to be done. 

Best,

**Comment by arlogriffiths** [comment]
Thanks! Could you just strip off the letters xml before the suffix .xml?

Capture d’écran 2022-12-14 à 16 18 50

**Comment by ajaniak** [comment]
My mistake in the filename should be resolved now.

**Pull request merged**
